INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (85000, 1, 'Игровой 200 Мбит/с', 85000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (80000, 1, 'Игровой 4 Мбит/с', 80000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (89000, 1, 'Домашний Интернет 200', 89000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (69000, 1, 'Домашний Интернет 100', 69000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (59000, 1, 'Домашний Интернет 80', 59000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (48000, 1, 'Домашний Интернет 45', 48000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (34900, 1, 'Домашний Интернет 8', 34900);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (32000, 2, 'Твой стартовый', 32000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (42000, 2, 'Твой оптимальный', 42000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (52000, 2, 'Твой продвинутый', 52000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (62000, 2, 'Твой премьерный', 62000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (170000, 2, 'Твой максимальный', 170000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (23000, 3, 'Популярный', 23000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (35000, 3, 'HD-Премиум', 35000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (19900, 3, 'Amedia Premium', 19900);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (9000, 3, 'Ночной', 9000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (21900, 3, 'Наш Футбол', 21900);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (38000, 3, 'ПЛЮС ФУТБОЛ', 38000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (45500, 4, 'Безлимитный', 45500);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (34000, 4, 'Абонентский', 34000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (34000, 4, 'Комбинированный 400', 34000);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (25100, 4, 'Комбинированный 100', 25100);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (34500, 4, 'Выходной', 34500);
INSERT INTO `old-hotel_rt-dev`.service (price_per_month, category_id, name, connection_cost) VALUES (20500, 4, 'Повременный', 20500);
